##DEM Processing=name
##boundaries=vector
##zvalueslope=number 111120
##climatena=raster
##slopedegrees=output raster
##tri=output raster
outputs_SAGACLIPGRIDWITHPOLYGON_1=processing.runalg('saga:clipgridwithpolygon', climatena,boundaries,None)
outputs_GDALOGRWARPREPROJECT_1=processing.runalg('gdalogr:warpreproject', outputs_SAGACLIPGRIDWITHPOLYGON_1['OUTPUT'],'','EPSG:4326','-9999',0.0,0,1,4,75.0,6.0,1.0,True,0,True,None,None)
outputs_GDALOGRSLOPE_1=processing.runalg('gdalogr:slope', outputs_GDALOGRWARPREPROJECT_1['OUTPUT'],1.0,True,True,False,zvalueslope,slopedegrees)
outputs_GDALOGRTRITERRAINRUGGEDNESSINDEX_1=processing.runalg('gdalogr:triterrainruggednessindex', outputs_GDALOGRWARPREPROJECT_1['OUTPUT'],1.0,True,tri)
outputs_SCRIPTCLEARTMPFOLDER_1=processing.runalg('script:cleartmpfolder', )