##Huglin Index=name
##maxtemperature=raster
##mintemperature=raster
##huglinvalues=raster
##outputfile=output raster
##huglinvalues=output raster
outputs_GDALOGRRASTERCALCULATOR_1=processing.runalg('gdalogr:rastercalculator', maxtemperature,'4',mintemperature,'4',huglinvalues,'1',maxtemperature,'5',mintemperature,'5',huglinvalues,'1','(((((A-10)+(B-10))/2)*C)*30)+(((((D-10)+(E-10))/2)*F)*31)','-9999',5,None,None)
outputs_GDALOGRRASTERCALCULATOR_3=processing.runalg('gdalogr:rastercalculator', maxtemperature,'8',mintemperature,'8',huglinvalues,'1',maxtemperature,'9',mintemperature,'9',huglinvalues,'1','(((((A-10)+(B-10))/2)*C)*31)+(((((D-10)+(E-10))/2)*F)*30)','-9999',5,None,None)
outputs_GDALOGRRASTERCALCULATOR_2=processing.runalg('gdalogr:rastercalculator', maxtemperature,'6',mintemperature,'6',huglinvalues,'1',maxtemperature,'7',mintemperature,'7',huglinvalues,'1','(((((A-10)+(B-10))/2)*C)*30)+(((((D-10)+(E-10))/2)*F)*31)','-9999',5,None,None)
outputs_GDALOGRRASTERCALCULATOR_4=processing.runalg('gdalogr:rastercalculator', outputs_GDALOGRRASTERCALCULATOR_1['OUTPUT'],'1',outputs_GDALOGRRASTERCALCULATOR_3['OUTPUT'],'1',outputs_GDALOGRRASTERCALCULATOR_2['OUTPUT'],'1',None,'1',None,'1',None,'1','A+B+C','-9999',5,None,None)
outputs_SAGARASTERCALCULATOR_1=processing.runalg('saga:rastercalculator', outputs_GDALOGRRASTERCALCULATOR_4['OUTPUT'],[],'g1*(g1>0)',True,7,huglinvalues)
